# Generated by Django 4.0.4 on 2022-07-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategory',
            new_name='category',
        ),
    ]
